### ISSUE TITLE
Error: undefined TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Dextererials** [kaibloecker/semantic-release-docker-gitlab-ci#33]
I am getting an error message `undefined TypeError: Cannot read properties of undefined (reading 'split')` when I try to add the plugin `semantic-release-docker-gitlab-ci`. The error is getting thrown from `semantic-release-docker-gitlab-ci/src/verify.js:35:1` Not sure what I am doing wrong. Here is my config files:

```
stages:
  - build
  - release

# Build docker image
build:
  image: docker:20.10
  stage: build
  dependencies:
    - setup-netrc
  services:
    - docker:23-dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --secret id=netrc,src=netrc/.netrc --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Run Release
semantic-release:
  image: node:lts
  stage: release
  variables:
    GITLAB_TOKEN: ${GITLAB_ACCESS_TOKEN}
  before_script:
    - apt-get update
    - npm install semantic-release @semantic-release/gitlab @semantic-release/release-notes-generator @semantic-release/commit-analyzer semantic-release-docker-gitlab-ci
  script:
    - npx semantic-release
  ```
